// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_iynj57XA0WendW9a3yqpntNMuKEekEI',
    appId: '1:54578731315:web:1c64ccd9b3876061180646',
    messagingSenderId: '54578731315',
    projectId: 'reminders-app-712cf',
    authDomain: 'reminders-app-712cf.firebaseapp.com',
    storageBucket: 'reminders-app-712cf.appspot.com',
    measurementId: 'G-EZCCV0ZKPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLC2rime7-kZm_rtIUz7xfBaNUz99El3o',
    appId: '1:54578731315:android:80e473a74cc2af81180646',
    messagingSenderId: '54578731315',
    projectId: 'reminders-app-712cf',
    storageBucket: 'reminders-app-712cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-hxMILtd1NZksOinuWKz4ea8oaL8W_8',
    appId: '1:54578731315:ios:c6ed0e67b2165839180646',
    messagingSenderId: '54578731315',
    projectId: 'reminders-app-712cf',
    storageBucket: 'reminders-app-712cf.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY-hxMILtd1NZksOinuWKz4ea8oaL8W_8',
    appId: '1:54578731315:ios:c6ed0e67b2165839180646',
    messagingSenderId: '54578731315',
    projectId: 'reminders-app-712cf',
    storageBucket: 'reminders-app-712cf.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_iynj57XA0WendW9a3yqpntNMuKEekEI',
    appId: '1:54578731315:web:3c43a3431c1ac576180646',
    messagingSenderId: '54578731315',
    projectId: 'reminders-app-712cf',
    authDomain: 'reminders-app-712cf.firebaseapp.com',
    storageBucket: 'reminders-app-712cf.appspot.com',
    measurementId: 'G-HJSLK7D4FT',
  );
}
